version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  rest-server:
    build: backend/rest
    container_name: rest-server-container
    ports:
      - "8081:8081"
    volumes:
      - ./backend/rest/target:/app
    command: ["java", "-jar", "/app/rest-application.jar"]
    depends_on:
      - postgres
  angular-frontend:
    build: frontend/webpage
    container_name: webpage-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rest-server